<?php
/**
 * *********************************************************************************
 *    @package    com_joomgallery                                                 **
 *    @author     JoomGallery::ProjectTeam <team@joomgalleryfriends.net>          **
 *    @copyright  2008 - 2026  JoomGallery::ProjectTeam                           **
 *    @license    GNU General Public License version 3 or later                   **
 * *********************************************************************************
 */

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') || die;
// phpcs:enable PSR1.Files.SideEffects

use Joomla\CMS\Language\Text;

/**
 * Array defining the exif codes
 *
 * @package JoomGallery
 * @since   4.0.0
 */
$exif_config_array = [
  "IFD0" => [
    270 => [  'Attribute'   => "ImageDescription",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_IMAGEDESCRIPTION'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_IMAGEDESCRIPTION_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
    271 => [  'Attribute'   => "Make",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_MAKE'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_MAKE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
    272 => [  'Attribute'   => "Model",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_MODEL'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_MODEL_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
    274 => [  'Attribute'   => "Orientation",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_1'),
                          2 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_2'),
                          3 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_3'),
                          4 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_4'),
                          5 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_5'),
                          6 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_6'),
                          7 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_7'),
                          8 => Text::_('COM_JOOMGALLERY_IFD0_ORIENTATION_8'),
            ],
    282 => [  'Attribute'   => "XResolution",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_XRESOLUTION'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_XRESOLUTION_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_IFD0_DOTSPERRESOLUTIONUNIT'),
            ],
    283 => [  'Attribute'   => "YResolution",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_YRESOLUTION'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_YRESOLUTION_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_IFD0_DOTSPERRESOLUTIONUNIT'),
            ],
    296 => [  'Attribute'   => "ResolutionUnit",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT_1'),
                          2 => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT_2'),
                          3 => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT_3'),
                          4 => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT_4'),
                          5 => Text::_('COM_JOOMGALLERY_IFD0_RESOLUTIONUNIT_5'),
            ],
    305 => [  'Attribute'   => "Software",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_SOFTWARE'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_SOFTWARE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
    306 => [  'Attribute'   => "DateTime",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_DATETIME'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_DATETIME_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
    318 => [  'Attribute'   => "WhitePoint",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_WHITEPOINT'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_WHITEPOINT_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
    319 => [  'Attribute'   => "PrimaryChromaticities",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_PRIMARYCHROMATICITIES'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_PRIMARYCHROMATICITIES_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
    529 => [  'Attribute'   => "YCbCrCoefficients",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_YCBCRCOEFFICIENTS'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_YCBCRCOEFFICIENTS_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
    531 => [  'Attribute'   => "YCbCrPositioning",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_YCBCRPOSITIONING'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_YCBCRPOSITIONING_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_IFD0_YCBCRPOSITIONING_1'),
                          2 => Text::_('COM_JOOMGALLERY_IFD0_YCBCRPOSITIONING_2'),
            ],
    532 => [  'Attribute'   => "ReferenceBlackWhite",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_REFERENCEBLACKWHITE'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_REFERENCEBLACKWHITE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
    315 => [  'Attribute'   => "Artist",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_ARTIST'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_ARTIST_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
  33432 => [  'Attribute'   => "Copyright",
              'Name'        => Text::_('COM_JOOMGALLERY_IFD0_COPYRIGHT'),
              'Description' => Text::_('COM_JOOMGALLERY_IFD0_COPYRIGHT_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
  ],

  'EXIF' => [
  33434 => [  'Attribute'   => "ExposureTime",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSURETIME'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSURETIME_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SECONDS'),
            ],
  33437 => [  'Attribute'   => "FNumber",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FNUMBER'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FNUMBER_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
  34850 => [  'Attribute'   => "ExposureProgram",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_3'),
                          4 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_4'),
                          5 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_5'),
                          6 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_6'),
                          7 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_7'),
                          8 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREPROGRAM_8'),
            ],
  34855 => [  'Attribute'   => "ISOSpeedRatings",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_ISOSPEEDRATINGS'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_ISOSPEEDRATINGS_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Short",
              'Units'       => "",
            ],
  36864 => [  'Attribute'   => "ExifVersion",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFVERSION'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFVERSION_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Undefined",
              'Units'       => "",
            ],
  36867 => [  'Attribute'   => "DateTimeOriginal",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_DATETIMEORIGINAL'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_DATETIMEORIGINAL_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
  36868 => [  'Attribute'   => "DateTimeDigitized",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_DATETIMEDIGITIZED'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_DATETIMEDIGITIZED_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
  37121 => [  'Attribute'   => "ComponentsConfiguration",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_COMPONENTSCONFIGURATION'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_COMPONENTSCONFIGURATION_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Undefined",
              'Units'       => "",
            ],
  37122 => [  'Attribute'   => "CompressedBitsPerPixel",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_COMPRESSEDBITSPERPIXEL'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_COMPRESSEDBITSPERPIXEL_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_COMPRESSEDBITSPERPIXEL_UNIT'),
            ],
  37377 => [  'Attribute'   => "ShutterSpeedValue",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SHUTTERSPEEDVALUE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SHUTTERSPEEDVALUE_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Signed Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_SHUTTERSPEEDVALUE_UNIT'),
            ],
  37378 => [  'Attribute'   => "ApertureValue",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_APERTUREVALUE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_APERTUREVALUE_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_APERTUREVALUE_UNIT'),
            ],
  37379 => [  'Attribute'   => "BrightnessValue",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_BRIGHTNESSVALUE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_BRIGHTNESSVALUE_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Signed Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_BRIGHTNESSVALUE_UNIT'),
            ],
  37380 => [  'Attribute'   => "ExposureBiasValue",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREBIASVALUE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREBIASVALUE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Signed Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREBIASVALUE_UNIT'),
            ],
  37381 => [  'Attribute'   => "MaxApertureValue",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_MAXAPERTUREVALUE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_MAXAPERTUREVALUE_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_APERTUREVALUE_UNIT'),
            ],
  37382 => [  'Attribute'   => "SubjectDistance",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Signed Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCE_UNIT'),
            ],
  37383 => [  'Attribute'   => "MeteringMode",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_3'),
                          4 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_4'),
                          5 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_5'),
                          6 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_6'),
                        255 => Text::_('COM_JOOMGALLERY_SUBIFD_METERINGMODE_255'),
            ],
  37384 => [  'Attribute'   => "LightSource",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_3'),
                          4 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_4'),
                          9 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_9'),
                          10 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_10'),
                          11 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_11'),
                          12 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_12'),
                          13 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_13'),
                          14 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_14'),
                          15 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_15'),
                          17 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_17'),
                          18 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_18'),
                          19 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_19'),
                          20 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_20'),
                          21 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_21'),
                          22 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_22'),
                          23 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_23'),
                          24 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_24'),
                        255 => Text::_('COM_JOOMGALLERY_SUBIFD_LIGHTSOURCE_255'),
            ],
  37385 => [  'Attribute'   => "Flash",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_1'),
                          5 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_5'),
                          7 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_7'),
                          8 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_8'),
                          9 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_9'),
                          13 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_13'),
                          15 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_15'),
                          16 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_16'),
                          20 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_20'),
                          24 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_24'),
                          25 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_25'),
                          29 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_29'),
                          31 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_31'),
                          32 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_32'),
                          48 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_48'),
                          65 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_65'),
                          69 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_69'),
                          71 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_71'),
                          73 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_73'),
                          77 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_77'),
                          79 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_79'),
                          80 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_80'),
                          88 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_88'),
                          89 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_89'),
                          93 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_93'),
                          95 => Text::_('COM_JOOMGALLERY_SUBIFD_FLASH_95'),
            ],
  37386 => [  'Attribute'   => "FocalLength",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALLENGTH'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALLENGTH_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALLENGTH_UNIT'),
            ],
  37510 => [  'Attribute'   => "UserComment",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_USERCOMMENT'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_USERCOMMENT_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Undefined",
              'Units'       => "",
            ],
  // 37520 => [  'Attribute'   => "SubsecTime",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SUBSECTIME'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SUBSECTIME_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "ASCII String",
  //             'Units'       => "",
  //           ],
  // 37521 => [  'Attribute'   => "SubsecTimeOriginal",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SUBSECTIMEORIGINAL'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SUBSECTIMEORIGINAL_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "ASCII String",
  //             'Units'       => "",
  //           ],
  // 37522 => [  'Attribute'   => "SubsecTimeDigitized",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SUBSECTIMEDIGITIZED'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SUBSECTIMEDIGITIZED_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "ASCII String",
  //             'Units'       => "",
  //           ],
  // 40960 => [  'Attribute'   => "FlashPixVersion",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FLASHPIXVERSION'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FLASHPIXVERSION_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "Undefined",
  //             'Units'       => "",
  //           ],
  40961 => [  'Attribute'   => "ColorSpace",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_COLORSPACE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_COLORSPACE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_COLORSPACE_SRGB'),
                      65535 => Text::_('COM_JOOMGALLERY_SUBIFD_COLORSPACE_65535'),
            ],
  40962 => [  'Attribute'   => "ExifImageWidth",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFIMAGEWIDTH'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFIMAGEWIDTH_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Short/Long",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFIMAGEWIDTHLENGTH_UNIT'),
            ],
  40963 => [  'Attribute'   => "ExifImageLength",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFIMAGELENGTH'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFIMAGELENGTH_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Short/Long",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFIMAGEWIDTHLENGTH_UNIT'),
            ],
  // 40964 => [  'Attribute'   => "RelatedSoundFile",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_RELATEDSOUNDFILE'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_RELATEDSOUNDFILE_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "ASCII String",
  //             'Units'       => "",
  //           ],
  // 40965 => [  'Attribute'   => "ExifInteroperabilityOffset",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFINTEROPERABILITYOFFSET'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXIFINTEROPERABILITYOFFSET_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "Unsigned Long",
  //             'Units'       => "",
  //           ],
  41486 => [  'Attribute'   => "FocalPlaneXResolution",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANEXRESOLUTION'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANEXRESOLUTION_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANEXYRESOLUTION_UNIT'),
            ],
  41487 => [  'Attribute'   => "FocalPlaneYResolution",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANEYRESOLUTION'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANEYRESOLUTION_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANEXYRESOLUTION_UNIT'),
            ],
  41488 => [  'Attribute'   => "FocalPlaneResolutionUnit",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANERESOLUTIONUNIT'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANERESOLUTIONUNIT_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANERESOLUTIONUNIT_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANERESOLUTIONUNIT_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALPLANERESOLUTIONUNIT_3'),
            ],
  41493 => [  'Attribute'   => "ExposureIndex",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREINDEX'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREINDEX_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
  41495 => [  'Attribute'   => "SensingMethod",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_3'),
                          4 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_4'),
                          5 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_5'),
                          7 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_7'),
                          8 => Text::_('COM_JOOMGALLERY_SUBIFD_SENSINGMETHOD_8'),
            ],
  41728 => [  'Attribute'   => "FileSource",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FILESOURCE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FILESOURCE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Undefined",
              'Units'       => "",
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_FILESOURCE_3'),
            ],
  41729 => [  'Attribute'   => "SceneType",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SCENETYPE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SCENETYPE_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Undefined",
              'Units'       => "",
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_SCENETYPE_1'),
            ],
  41986 => [  'Attribute'   => "ExposureMode",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREMODE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREMODE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREMODE_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREMODE_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_EXPOSUREMODE_2'),
            ],
  41987 => [  'Attribute'   => "WhiteBalance",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_WHITEBALANCE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_WHITEBALANCE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_WHITEBALANCE_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_WHITEBALANCE_1'),
            ],
  41988 => [  'Attribute'   => "DigitalZoomRatio",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_DIGITALZOOMRATIO'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_DIGITALZOOMRATIO_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
  41989 => [  'Attribute'   => "FocalLengthIn35mmFilm",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALLENGTHIN35MMFILM'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALLENGTHIN35MMFILM_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Unsigned Short",
              'Units'       => Text::_('COM_JOOMGALLERY_SUBIFD_FOCALLENGTHIN35MMFILM_UNIT'),
            ],
  41990 => [  'Attribute'   => "SceneCaptureType",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SCENECAPTURETYPE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SCENECAPTURETYPE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_SCENECAPTURETYPE_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_SCENECAPTURETYPE_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_SCENECAPTURETYPE_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_SCENECAPTURETYPE_3'),
            ],
  41991 => [  'Attribute'   => "GainControl",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL_3'),
                          4 => Text::_('COM_JOOMGALLERY_SUBIFD_GAINCONTROL_4'),
            ],
  41992 => [  'Attribute'   => "Contrast",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_CONTRAST'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_CONTRAST_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_CONTRAST_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_CONTRAST_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_CONTRAST_2'),
            ],
  41993 => [  'Attribute'   => "Saturation",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SATURATION'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SATURATION_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_SATURATION_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_SATURATION_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_SATURATION_2'),
            ],
  41994 => [  'Attribute'   => "Sharpness",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SHARPNESS'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SHARPNESS_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_SHARPNESS_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_SHARPNESS_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_SHARPNESS_2'),
            ],
  // 41995 => [  'Attribute'   => "DeviceSettingDescription",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_DEVICESETTINGDESCRIPTION'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_DEVICESETTINGDESCRIPTION_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "Undefined",
  //             'Units'       => "",
  //           ],
  41996 => [  'Attribute'   => "SubjectDistanceRange",
              'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCERANGE'),
              'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCERANGE_DESCRIPTION'),
              'Calculation' => "Array",
              'Format'      => "Unsigned Short",
              'Units'       => "",
                          0 => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCERANGE_0'),
                          1 => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCERANGE_1'),
                          2 => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCERANGE_2'),
                          3 => Text::_('COM_JOOMGALLERY_SUBIFD_SUBJECTDISTANCERANGE_3'),
            ],
  // 42016 => [  'Attribute'   => "ImageUniqueID",
  //             'Name'        => Text::_('COM_JOOMGALLERY_SUBIFD_IMAGEUNIQUEID'),
  //             'Description' => Text::_('COM_JOOMGALLERY_SUBIFD_IMAGEUNIQUEID_DESCRIPTION'),
  //             'Calculation' => "",
  //             'Format'      => "",
  //             'Units'       => "",
  //            ],
  ],
  "GPS" => [
      // 0 => [  'Attribute'   => "GPSVersionID",
      //         'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSVERSIONID'),
      //         'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSVERSIONID_DESCRIPTION'),
      //         'Calculation' => "",
      //         'Format'      => "Byte",
      //         'Units'       => "",
      //       ],
      1 => [  'Attribute'   => "GPSLatitudeRef",
              'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSLATITUDEREF'),
              'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSLATITUDEREF_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
      2 => [  'Attribute'   => "GPSLatitude",
              'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSLATITUDE'),
              'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSLATITUDE_DESCRIPTION'),
              'Calculation' => "DegMinSec",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
      3 => [  'Attribute'   => "GPSLongitudeRef",
              'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSLONGITUDEREF'),
              'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSLONGITUDEREF_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "ASCII String",
              'Units'       => "",
            ],
      4 => [  'Attribute'   => "GPSLongitude",
              'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSLONGITUDE'),
              'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSLONGITUDE_DESCRIPTION'),
              'Calculation' => "DegMinSec",
              'Format'      => "Unsigned Rational",
              'Units'       => "",
            ],
      5 => [  'Attribute'   => "GPSAltitudeRef",
              'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSALTITUDEREF'),
              'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSALTITUDEREF_DESCRIPTION'),
              'Calculation' => "",
              'Format'      => "Byte",
              'Units'       => "",
            ],
      6 => [  'Attribute'   => "GPSAltitude",
              'Name'        => Text::_('COM_JOOMGALLERY_GPS_GPSALTITUDE'),
              'Description' => Text::_('COM_JOOMGALLERY_GPS_GPSALTITUDE_DESCRIPTION'),
              'Calculation' => "Denum",
              'Format'      => "Unsigned Rational",
              'Units'       => Text::_('COM_JOOMGALLERY_GPS_GPSALTITUDE_UNIT'),
            ],
  ],
];
